# docker-compose.yml file
version: '3'

services:
   nginx:
    image: nginx:1.16.0-alpine
    container_name: "nginx1.16"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site/site.conf:/etc/nginx/sites-available/site.conf:ro
      - ./data/:/var/www/:ro
    ports:
      - "80:80"
